### ISSUE TITLE
Implement TLS handshake for 1.1,1.2

### ISSUE THREAD

**Issue by acagliano** [cagstech/lwip-ce#21]
Only if we want to support all versions of TLS.

**Comment by acagliano** [comment]
All servers must support TLS 1.3 by Jan 2024. There's no need to support anything else.

**Comment by tkbstudios** [comment]
No TLS1.2 ? It's still used a lot.

**Comment by acagliano** [comment]
I think you're confusing "offered" with "used" and there's an important distinction. TLS 1.3 is now the defacto standard/recommendation by NIST `As of Jan 24, 2024 all servers *shall* support TLS 1.3 and *should* support 1.2"`. Unless a server is non-complaint if you inform you want 1.3, you get 1.3; there's no need to implement client support for anything else. Servers support it for those clients that still don't support 1.3, but we do.

I have other reasons for wanting to nix 1.2: the handshake process is longer and more complicated. ie-more state memory to hold, more slow math. This isn't a computer where the difference will be like tenths of a second... it's a calculator where the difference will be several seconds. What's the point?

I invite @commandblockguy to share their thoughts as well.

**Comment by acagliano** [comment]
Closing issue. Feature will not be provided built-in. Support can be added if people want it by external extension/library layered over ciphersuite API.
